CC=g++
CFLAGS=-std=c++11 
SOURCES=hf.cpp 4.cpp
OBJECTS=$(SOURCES:.cpp=.o)
EXECUTABLE=4

default:
	g++ -I /Users/ruheedcunha/Desktop/playground/eigen -std=c++11 -c hf.cpp
	g++ -I /Users/ruheedcunha/Desktop/playground/eigen -std=c++11 -c 4.cpp
	g++ -I /Users/ruheedcunha/Desktop/playground/eigen -std=c++11 hf.o 4.o -o 4
