CC=g++
CFLAGS=-std=c++11 
SOURCES=hf.cpp 3.cpp
OBJECTS=$(SOURCES:.cpp=.o)
EXECUTABLE=2

default:
	g++ -I /Users/ruheedcunha/Desktop/playground/eigen -std=c++11 -c hf.cpp
	g++ -I /Users/ruheedcunha/Desktop/playground/eigen -std=c++11 -c 3.cpp
	g++ -I /Users/ruheedcunha/Desktop/playground/eigen -std=c++11 hf.o 3.o -o 3
