CC=g++
CFLAGS=-std=c++11 
SOURCES=hf.cpp 8.cpp
OBJECTS=$(SOURCES:.cpp=.o)
EXECUTABLE=8

default:
	g++ -I /Users/ruheedcunha/Desktop/playground/eigen -std=c++11 -c hf.cpp
	g++ -I /Users/ruheedcunha/Desktop/playground/eigen -std=c++11 -c 8.cpp
	g++ -I /Users/ruheedcunha/Desktop/playground/eigen -std=c++11 hf.o 8.o -o 8
